export type {
  SeverityLevel,
  CarTier,
  DefectCategory,
  CellType,
  LogType,
  DefectType,
  DefectInstance,
  Car,
  CarHistoryEntry,
  Player,
  Debt,
  BoardCell,
  SoloQuest,
  GameNews,
  LogEntry,
  GameState,
  RoomState,
  SyncActionPayload,
  ServerToClientEvents,
  ClientToServerEvents,
  GameEventType,
  GameEventLog,
} from './types.js';

export { HEALTH_PENALTIES, GAME_MAP } from './types.js';

export {
  SEVERITY_COST_RANGES,
  OWNERSHIP_TAX_RATES,
  PROFIT_MARGINS,
  RENT_INCOME,
  deterministicMultiplier,
  calculateCarHealth,
  applyNewsEffects,
  calculateCurrentMarketValue,
  calculateSellPrice,
  calculateOwnershipTax,
  calculateRentIncome,
  generateRepairCost,
} from './businessLogic.js';
